### PR TITLE
Update rest-client to 2.1.0

### PR DESCRIPTION
**Pull request by andrii-rymar**
Related to #50

Updating rest-client to it's latest version to avoid dependency conflicts with a lot of other libs locked with 2.1.0.

### CODE REVIEW

**Comment by andrii-rymar** [comment]
@samfader I'm seeing Travis tests failing due to missing API token. Guess we can add an encrypted token into .travis.yml but it will be accessible only from the main repo, not from the forks. Have no ideas how can we resolve it... 

Anyway tests are good locally.

**Comment by samfader** [comment]
Looks good @andrii-rymar. Are you open to pushing the gem update to rubygems (https://guides.rubygems.org/publishing/)? I can give you push permissions if that's something you'd be open to.

**Comment by andrii-rymar** [comment]
@samfader sure, let's do it. Guess we need another PR to bump whole gem to 2.3.1, right?

**Comment by samfader** [comment]
@andrii-rymar Yes, would need that as well if you don't mind. Can you share your email I should use to send Rubygems permissions? Let me know if you'd prefer to share off of a public thread.

**Comment by andrii-rymar** [comment]
@samfader here is an email you can send it: onegloriouspenguin@gmail.com. Thanks

**Comment by samfader** [comment]
@andrii-rymar Do you have a rubygems.org account with that email? Says it couldn't find this user...

**Comment by andrii-rymar** [comment]
@samfader it should be in place now.

**Comment by samfader** [comment]
@andrii-rymar done, thanks. Will approve other PR now.

**Comment by andrii-rymar** [comment]
@samfader thanks

**Pull request merged**
